import fs from 'node:fs';

const TARGET = '/Users/apple/Downloads/AI行业创业方向与生态建设讨论_原文.md';
const lines = fs.readFileSync(TARGET, 'utf8').split('\n');
const headers = [];
for (let i = 2103; i <= 2401; i++) {
  const l = lines[i - 1];
  if (/^(Patrick|Ryan|叶奇意)\s+\d{2}:\d{2}:\d{2}\s*$/.test(l)) headers.push(l);
}
if (headers.length !== 100) throw new Error('header count ' + headers.length);

// fix bodies: one string per block (index 0..99)
const fix = [
  `just easy efficiency. Yeah, I just .`,
  `hate AI assisted human human mass.`,
  `I just hate AI, but we have to use it every day. No, I think AI is great. But AI is a tool. So like execute tasks, not to like be a crutch for the fact that I can't talk .`,
  `to somebody um I see.`,
  `So you're gonna hate our product.`,
  `I just read. Maybe I'm old fashioned.`,
  `No, I just did.`,
  `I just can't read it. I can't read it anymore. I don't want to talk to. I just don't want to communicate.`,
  `Talking is even worse.`,
  `so bad. Yeah yeah. You should also think about some consumer stuff that has .`,
  `nothing to do with .`,
  `AI yeah yeah sure like we we've been looking at a lot of sports. We invested in like a juice, juice company, sort of a um doing like liquid salad kind of things. Oh no. I don't think actually that the biggest winners will be people .`,
  `who only focus .`,
  `on AI. Actually um like sports is great because there's no AI. It's kind of AI proof and um and that .`,
  `are all, they are all Chinese company.`,
  `Um the the juice company is a is a Chinese American guy who lived in Beijing for like twelve years. He's a marketer and um but he's he's building it for the US market.`,
  `He moved back to LA to do it. So it's not exactly true. But his suppliers here. So uh uh we met we met him in China before he moved back to LA. And we were for his first investors嗯嗯 and then yeah we've been we've been starting with sports. We think sports is really interesting yeah um and we're looking at shoes, sports drinks, high rocks competitors.`,
  `Do you know AUBL, AUBL? AUBL is like a college student basketball.`,
  `Oh, cool. Oh, yes.`,
  `I did hear about that. Yeah. And so called China investor. Yeah, yeah, yeah.`,
  `I think those kind of businesses are .`,
  `very interesting.`,
  `Yeah, yeah, yeah. And I think actually those types of founders, if you had them in the same community as tech founders, it would actually be very helpful because those founders understand marketing, yeah, yeah, sure sure. And brand building yeah. Actually the technology .`,
  `has a terrible that stuff, yeah yeah .`,
  `yeah yeah yeah yeah. So having an ecosystem like .`,
  `that also could be very helpful. Yeah um and we are we are something like that .`,
  `yeah yeah I think it's totally fine to have like if you find a really great person who is really good at, like I don't know, ski boots, just like you know just do it right like like it's it's there's there's gonna be so much spending in sports in the next ten years because everyone's going to focus on health, longevity, life.`,
  `life experiences yeah yeah yeah .`,
  `people are not going to spend time on the computer anymore so they're just gonna like .`,
  `have other things they want to do yeah .`,
  `so it's it's gonna be a, I think, uh, a big uncorrelated trade. What's correlated. But it's like it's not related to AI and it won't be eaten by AI. I think it has benefits because marketing is going to get easier. Like, yeah you can scale brand yeah.`,
  `yeah, yeah.`,
  `yeah yeah. I think I think there's I think now is a good time to actually bet on things that vcs don't like like I think sport, I think many, very few vcs are doing sports or sports related things. And for reality.`,
  `yeah.`,
  `it's going to be like people people are going to hate AI. They're not going to want to spend time on it yeah. They're going to just want to be with other people and they want to do real things yeah.`,
  `especially in Asia.`,
  `Well, III think I really don't. I really it's sort of like when people detox already and they want to .`,
  `read a book and they .`,
  `want to be .`,
  `on their phone, right? And then ten times more extreme, yeah yeah sure. And my friend in LA, uh, his actually doing a pillow brand, details pillow brand. And he's the, uh, growing so fast yeah and like forty dollars a pillow yeah and they'll sell so well yeah what's .`,
  `the pillow .`,
  `do uh is like the pillow uh the the shape is is, uh is very nice okay yeah and echo to Patrick uh because people has more consensus of wellness yeah yeah and they like, uh uh ten years ago we we uh we don't need very healthy pillow yeah or something like that and today we we we have like a sleep yeah we have whoop or ring and so people have more like a favor to buy a healthy pillow yeah yeah yeah yeah I got Eight Sleep .`,
  `earlier this summer and it's amazing and like, yeah we actually .`,
  `have a once a year yeah I mean you sleep super .`,
  `Well it's like if you make your bed, you're gonna make the investment right yeah and every generation has a new mattress. New pillow I mean Tempur-Pedic was like the original brand yeah and then there was like all these special foam mattresses like ten years ago that and you know I think the difference now is like you can be much more technology enabled, right? You can put like the 8 Sleep has sensors in it.`,
  `And so I think you can build a subscription business, right? Yeah, but I think health, health, wellness, sports, cool. We were talking with someone about cold plunging. Like, I like ice baths. You go into an ice bath.`,
  `Oh, I see. Bing. I, I, yeah, yeah, yeah, yeah, yeah. So, yeah.`,
  `uh, like in Hong Kong, all these sauna ice bath clubs are becoming very popular. They keep opening new ones.`,
  `I see it's all bubble.`,
  `It's very early in the bubble.`,
  `Yeah but it's not a problem.`,
  `So you don't like us. I like that.`,
  `But yeah yeah yeah yeah.`,
  `But but but but it's it's uh that kind of wellness business is doing, and it's expensive. It's like it's it's it's it's like forty bucks a .`,
  `time or something. Yeah three hundred HKD. Oh, per session.`,
  `per session.`,
  `Okay.`,
  `but you happily do it because you like you want it. Yeah it's great business. And so um and they're full, like you go any time of the day and it's like full of people.`,
  `These are not like empty gyms. They're like people are going and they really enjoy it. And like they've really created a way to make people that are highly engaged. So again, it's sort of a new wellness thing that that works and has nothing to do with computers.`,
  `Um it's the opposite it's .`,
  `feeling very strong temperatures in your body right like yeah that's ah that makes you feel very human .`,
  `and it's like very .`,
  `real yeah so anyway, I would yeah I would recommend that not just you know I would I would try to find if if people are doing interesting things in other areas and you think that it fits this tailwind like wellness or something, I wouldn't be afraid to do, take a bet on something like that yeah yeah.`,
  `And I .`,
  `also see something .`,
  `like a robot battle .`,
  `fighting robots.`,
  `yeah. Uh it's like double E yeah it is actually a TV show yeah. And even people can like do something uh like like like. 忘记那个公司叫什么来。`,
  `预售的那个。`,
  `That you can and like the poly market yeah poly market yeah yeah you know there's .`,
  `a Russian betting website that that makes fake sports sports games. So the people can bet on them .`,
  `that is just a scam. No.`,
  `there's you know because it's a fake. This is just the equals response.`,
  `Maybe you should .`,
  `think of all example. The ball just goes in and people are betting on like who can and they create fake soccer leagues. And just so that people can bet on the soccer games.`,
  `they're real.`,
  `they're real games. But like, but they're not professional .`,
  `not .`,
  `professional yeah not professional, but these create amateur games. They just create games so people can bet on them, 没有。`,
  `Yeah, yeah, no.`,
  `I think it goes in both ways.`,
  `Like, people are gonna want to watch robots do something entertaining. Yeah, people want to watch humans do something more entertaining. Hm, right.`,
  `Like maybe there is a, maybe there is a world in which like there is technology involved in some things, right? Like but it just has to be more extreme. There's definitely a world where technology will be .`,
  `involved with some things, no, I don't know .`,
  `And I mean, for human sports, for example, like I'm thinking like first like a hyper shell, right? Like maybe they'll be like a way for people to sprint up a mountain with Hyper Shell, right? And there'll be a hyper shell games where people are just doing insane stuff with with exoskeletons.`,
  `right?`,
  `But yeah, yeah, I think so. I but I think the point is that .`,
  `uh although the enhanced games didn't do very well, did they.`,
  `I don't know, did that happen. Enhanced games was like this thing where everyone took steroids and then we would like to do the sports.`,
  `So it's like they paid the athletes a lot of .`,
  `money .`,
  `um yesterday some marketing yeah .`,
  `yeah but you can just yeah everyone. Hirox was steroids .`,
  `no no no it was the Olympics. It was like Olympics .`,
  `sports .`,
  `Oh, wow. Track and field .`,
  `and that they paid .`,
  `everybody who broke a world .`,
  `record of a million dollars, but actually not that many .`,
  `people broke even with the chemicals.`,
];

// polish bodies: array of paragraph strings per block (index 0..99)
const polish = [
  [`just easy efficiency. Yeah, I just .`],
  [`hate AI assisted human human mass.`],
  [`I just hate AI, but we have to use it every day. No, I think AI is great. But AI is a tool. It should execute tasks, not be a crutch for the fact that I can't talk.`,
   `译：我就是讨厌 AI，但每天又不得不用它。不，我觉得 AI 很棒，但它只是个工具。它应该执行任务，而不是因为我不会说话就成了我的拐杖。`],
  [`to somebody. I see.`,
   `译：跟人说话。我明白了。`],
  [`So you're gonna hate our product.`,
   `译：那你会讨厌我们的产品。`],
  [`I just read. Maybe I'm old fashioned.`,
   `译：我只是读书。也许我太老派了。`],
  [`No, I just did.`,
   `译：不，我就是这样。`],
  [`I just can't read it anymore. I don't want to talk. I just don't want to communicate.`,
   `译：我就是读不下去了。我不想说话，就是不想交流。`],
  [`Talking is even worse.`,
   `译：说话更糟。`],
  [`So bad. Yeah, you should also think about some consumer stuff that has .`,
   `译：太糟了。对，你也该想想一些跟……毫无关系的消费类的东西。`],
  [`nothing to do with .`],
  [`Yeah yeah sure, like we've been looking at a lot of sports. We invested in like a juice company, sort of doing like liquid salad kind of things. Oh no, I don't think actually that the biggest winners will be people .`,
   `译：对，就像我们看了很多体育项目。我们投了一家果汁公司，做的是液体沙拉那种东西。哦不，我其实不觉得最大的赢家会是那些只专注 AI 的人……`],
  [`who only focus .`],
  [`on AI. Actually, like sports is great because there's no AI. It's kind of AI proof, and that .`,
   `译：只专注 AI。其实像体育就很好，因为里面没有 AI，它算是种 AI 免疫的生意，而且那……`],
  [`are all, they are all Chinese company.`],
  [`The juice company is a Chinese American guy who lived in Beijing for like twelve years. He's a marketer, but he's building it for the US market.`,
   `译：这家果汁公司是一个华裔美国人做的，他在北京住了十二年。他是个做营销的，但产品是面向美国市场的。`],
  [`He moved back to LA to do it. So it's not exactly true, but his suppliers are here. We met him in China before he moved back to LA, and we were his first investors. We've been starting with sports. We think sports is really interesting, and we're looking at shoes, sports drinks, high rocks competitors.`,
   `译：他搬回洛杉矶来做这件事，所以说不完全准确，但供应商在这边。我们在他搬回洛杉矶之前就在中国认识了他，我们是他的第一批投资人。我们一直在看体育。我们觉得体育很有意思，还在看鞋、运动饮料、high rocks 的竞争对手。`],
  [`Do you know AUBL? AUBL is like a college student basketball.`,
   `译：你知道 AUBL 吗？AUBL 就像是一个大学生篮球联赛。`],
  [`Oh, cool. Oh, yes.`,
   `译：哦，酷。哦，是的。`],
  [`I did hear about that. Yeah. And so called China investor. Yeah, yeah, yeah.`,
   `译：我听说过。对，还有所谓的中国投资人。对对对。`],
  [`I think those kind of businesses are .`],
  [`very interesting.`],
  [`Yeah, yeah, yeah. And I think actually those types of founders, if you had them in the same community as tech founders, it would be very helpful, because those founders understand marketing, sure sure. And brand building. Actually the technology .`,
   `译：对。而且我觉得那类创始人，如果把他们和科技创始人放在同一个社区里，会很有帮助，因为他们懂营销，真的懂。还有品牌建设。其实技术……`],
  [`has a terrible that stuff, yeah yeah .`],
  [`yeah yeah yeah yeah. So having an ecosystem like .`],
  [`that also could be very helpful. Yeah, and we are something like that .`,
   `译：那也会很有帮助。对，我们也在做类似的事。`],
  [`Yeah, I think it's totally fine, like if you find a really great person who is really good at, I don't know, ski boots, just do it right. There's gonna be so much spending in sports in the next ten years, because everyone's going to focus on health, longevity, life.`,
   `译：对，我觉得这完全没问题。如果你找到一个真的很厉害的人，比如特别会做滑雪靴，那就直接去做。未来十年体育上会有巨大的投入，因为所有人都会关注健康、长寿、生活。`],
  [`life experiences yeah yeah yeah .`],
  [`people are not going to spend time on the computer anymore, so they're just gonna like .`],
  [`have other things they want to do yeah .`],
  [`So it's gonna be a big uncorrelated trade. What's correlated. But it's like, it's not related to AI, and it won't be eaten by AI. I think it has benefits, because marketing is gonna get easier. Like, yeah, you can scale a brand.`,
   `译：所以这会是一个巨大的、与 AI 不相关的投资方向。和 AI 相关的那些……但体育跟 AI 没关系，也不会被 AI 吃掉。我觉得它有个好处，就是营销会越来越容易。对，你可以把品牌做起来。`],
  [`yeah, yeah.`],
  [`Yeah. I think now is a good time to actually bet on things that vcs don't like. I think sport, I think very few vcs are doing sports or sports related things. And for reality.`,
   `译：对。我觉得现在是下注 VC 不喜欢的东西的好时机。我觉得很少有 VC 在做体育或体育相关的事情。而且，说真的。`],
  [`yeah.`],
  [`People are gonna hate AI. They're not gonna want to spend time on it. They're gonna want to be with other people and do real things.`,
   `译：人们会讨厌 AI，不想在它上面花时间。他们会想和别人待在一起，去做真实的事情。`],
  [`especially in Asia.`,
   `译：尤其是在亚洲。`],
  [`Well, I think I really don't. It's sort of like when people detox already and they want to .`,
   `译：嗯，我觉得我真的很不……就像人们已经戒断了一样，他们想要……`],
  [`read a book and they .`],
  [`want to be .`],
  [`on their phone, right? And it's gonna be ten times more extreme. Yeah yeah sure. And my friend in LA, he's actually doing a pillow brand, a details pillow brand. It's growing so fast, like forty dollars a pillow, and they sell so well. What's .`,
   `译：……玩手机，对吧？而且会严重十倍。对，还有我在洛杉矶的朋友，他在做一个枕头品牌，一个 details 的枕头品牌。增长特别快，一个枕头大概四十美元，卖得很好。它是什么……`],
  [`the pillow .`],
  [`the pillow, like, the shape is very nice. Okay. And echo to Patrick, because people have more consensus of wellness. Ten years ago we didn't need a very healthy pillow, or something like that. Today we have like a sleep, we have Whoop or ring, so people are more likely to buy a healthy pillow. I got Eight Sleep .`,
   `译：枕头，就是形状很好看。对，而且对 Patrick 来说也一样，因为人们对健康有了更多共识。十年前我们不需要多么健康的枕头之类的。今天我们有睡眠监测，有 Whoop 或者指环，所以人们更愿意买一个健康的枕头。我买了 Eight Sleep……`],
  [`earlier this summer, and it's amazing. And like, yeah, we actually .`],
  [`have a once a year. I mean, you sleep super .`],
  [`Well, it's like, if you make your bed, you're gonna make the investment, right? Every generation has a new mattress, new pillow. I mean, Tempur-Pedic was like the original brand. And then there were all these special foam mattresses like ten years ago. I think the difference now is you can be much more technology enabled, right? You can put like the 8 Sleep, it has sensors in it.`,
   `译：怎么说呢，如果你要置办你的床，你就会在这上面花钱，对吧？每一代人都有新的床垫、新的枕头。我的意思是，Tempur-Pedic 算是鼻祖品牌，然后十年前又冒出来一堆特殊的泡沫床垫。我觉得现在的区别是，它可以高度技术化，对吧？你可以放一个 8 Sleep，里面带传感器。`],
  [`So I think you can build a subscription business, right? But I think health, wellness, sports, cool. We were talking with someone about cold plunging. Like, I like ice baths. You go into an ice bath.`,
   `译：所以我觉得你可以做成订阅制生意，对吧？不过我觉得健康、养生、运动这些很酷。我们之前和人聊过冷水浴。比如我喜欢冰浴，你整个人进到冰水里。`],
  [`Oh, I see. Bing. Yeah, yeah, yeah, yeah, yeah. So, yeah.`,
   `译：哦，我懂了。Bing。对对对对对。所以，对。`],
  [`Like in Hong Kong, all these sauna ice bath clubs are becoming very popular. They keep opening new ones.`,
   `译：比如在香港，这些桑拿冰浴俱乐部正变得非常流行，一家接一家地开。`],
  [`I see it's all bubble.`,
   `译：我看这全是泡沫。`],
  [`It's very early in the bubble.`,
   `译：泡沫才刚刚开始。`],
  [`Yeah, but it's not a problem.`,
   `译：对，但这不是问题。`],
  [`So you don't like us. I like that.`,
   `译：所以你不喜欢我们。我喜欢这样。`],
  [`But yeah yeah yeah yeah.`],
  [`But that kind of wellness business is doing, and it's expensive. It's like forty bucks a .`,
   `译：但这种养生生意正在兴起，而且很贵。一次大概四十美元……`],
  [`time or something. Yeah, three hundred HKD. Oh, per session.`,
   `译：……一次之类的。对，三百港币。哦，按次收费。`],
  [`per session.`,
   `译：按次。`],
  [`Okay.`],
  [`but you happily do it, because you like it, you want it. Yeah, it's a great business. And they're full. You go any time of the day and it's full of people.`,
   `译：但你乐意去，因为你喜欢、你想要。对，这是门好生意。而且店里总是满的，你任何时候去都坐满了人。`],
  [`These are not like empty gyms. People are going and they really enjoy it. They've really created a way to make people highly engaged. So again, it's a new wellness thing that works and has nothing to do with computers.`,
   `译：这些不像空荡荡的健身房。人们真的会去，而且真的很享受。他们确实做出了一种让人高度投入的方式。所以这又是一种行得通的新养生模式，而且和电脑毫无关系。`],
  [`It's the opposite. It's .`],
  [`feeling very strong temperatures in your body, right? Yeah, that makes you feel very human .`,
   `译：感受身体里强烈的温度变化，对吧？对，那让你觉得自己非常像个人。`],
  [`and it's like very .`],
  [`real. So anyway, I would recommend that, not just, you know, I would try to find if people are doing interesting things in other areas, and you think it fits this tailwind, like wellness or something. I wouldn't be afraid to take a bet on something like that.`,
   `译：非常真实。所以总之我建议，不只是……你知道，我会去看看其他领域有没有人在做有意思的事，如果觉得它符合这股东风，比如养生之类的，就不要害怕去下注。`],
  [`And I .`],
  [`also see something .`],
  [`like a robot battle .`],
  [`fighting robots.`],
  [`Yeah. It's like double E, it's actually a TV show. And even people can do something like... 忘记那个公司叫什么来。`,
   `译：对。就像 double E，它其实是个电视节目。甚至人们可以做一些类似……（忘记那个公司叫什么来。）`],
  [`预售的那个。`],
  [`That you can, and like the poly market, poly market. Yeah yeah, you know there's .`,
   `译：你可以……就像 Polymarket 那样的预测市场，对，你知道有……`],
  [`a Russian betting website that makes fake sports games, so people can bet on them.`,
   `译：一个俄罗斯的博彩网站，专门做假体育比赛，好让人们下注。`],
  [`that is just a scam. No.`,
   `译：那就是个骗局。不。`],
  [`there's, you know, because it's a fake. This is just the equals response.`,
   `译：因为它是假的。这只是一个 equals response。`],
  [`Maybe you should .`],
  [`think of all example. The ball just goes in, and people are betting on like who can... and they create fake soccer leagues, just so that people can bet on the soccer games.`,
   `译：想想所有的例子。球就那么滚进去，人们赌谁能……他们造出假的足球联赛，就是为了让人们能赌这些比赛。`],
  [`they're real.`],
  [`they're real games, but they're not professional .`,
   `译：比赛是真的，但不够专业……`],
  [`not .`],
  [`not professional, but these create amateur games. They just create games so people can bet on them, 没有。`,
   `译：不专业，但他们造的是业余比赛。他们造比赛就是为了让人下注，没有。`],
  [`Yeah, yeah, no.`],
  [`I think it goes in both ways.`,
   `译：我觉得这事是双向的。`],
  [`Like, people are gonna want to watch robots do something entertaining. People want to watch humans do something more entertaining. Hm, right.`,
   `译：就像，人们会想看机器人做点有意思的事。人们也想看人类做更有意思的事。嗯，对吧。`],
  [`Like maybe there is a world in which technology is involved in some things, right? But it just has to be more extreme. There's definitely a world where technology will be .`,
   `译：也许会有这样一个世界，技术参与进某些事情里，对吧？但它必须更极端。肯定会有技术参与的……`],
  [`involved with some things, no, I don't know .`],
  [`And I mean, for human sports, for example, I'm thinking like, first like a hyper shell, right? Maybe there'll be a way for people to sprint up a mountain with Hyper Shell, right? There'll be Hyper Shell games where people are doing insane stuff with exoskeletons.`,
   `译：我的意思是，比如人类体育，我在想，先像 Hyper Shell 那样，对吧？也许以后会有一种方式，让人们穿着 Hyper Shell 冲上山，对吧？还会有 Hyper Shell 比赛，人们穿着外骨骼做各种疯狂的事。`],
  [`right?`],
  [`But yeah, I think so. But I think the point is that .`,
   `译：但我觉得是的。不过我觉得重点是……`],
  [`although the enhanced games didn't do very well, did they.`,
   `译：不过 Enhanced Games 当年做得并不好，是吧？`],
  [`I don't know, did that happen. Enhanced games was this thing where everyone took steroids and then would do the sports.`,
   `译：我不知道，有这事吗？Enhanced Games 就是那种所有人都吃类固醇、然后去参加比赛的东西。`],
  [`So it's like they paid the athletes a lot of .`],
  [`money .`],
  [`um yesterday some marketing yeah .`],
  [`yeah, but you can just, yeah, everyone. Hirox was steroids .`,
   `译：对，但你可以直接……对，所有人。Hirox 就是类固醇。`],
  [`no no no, it was the Olympics. It was like Olympics .`,
   `译：不不不，那是奥运会。就像是奥运会……`],
  [`sports .`],
  [`Oh, wow. Track and field .`,
   `译：哦，哇。田径……`],
  [`and that they paid .`],
  [`everybody who broke a world .`],
  [`record of a million dollars, but actually not that many .`],
  [`people broke even with the chemicals.`,
   `译：其实没多少人靠药物破纪录。`],
];

if (fix.length !== 100 || polish.length !== 100) throw new Error('body count ' + fix.length + '/' + polish.length);

function render(headers, bodies, mode) {
  let out = '';
  for (let i = 0; i < 100; i++) {
    out += headers[i] + '\n';
    if (mode === 'fix') {
      out += bodies[i] + '\n';
    } else {
      out += bodies[i].join('\n') + '\n';
    }
    if (i < 99) out += '\n';
  }
  return out;
}

const fixOut = render(headers, fix, 'fix');
const polOut = render(headers, polish, 'polish');

fs.mkdirSync('/Users/apple/Documents/deepseek/Working-Place/out/fix', { recursive: true });
fs.mkdirSync('/Users/apple/Documents/deepseek/Working-Place/out/polish', { recursive: true });
fs.writeFileSync('/Users/apple/Documents/deepseek/Working-Place/out/fix/c08.md', fixOut);
fs.writeFileSync('/Users/apple/Documents/deepseek/Working-Place/out/polish/c08.md', polOut);

console.log('fix lines:', fixOut.split('\n').length, 'polish lines:', polOut.split('\n').length);
